# Generated by Django 5.1.4 on 2025-01-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchqueue',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.match'),
        ),
    ]
