# Generated by Django 5.1.4 on 2025-01-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_diff',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='view_diff',
            field=models.BigIntegerField(default=0),
        ),
    ]
